const FORM_ACTIONS = {
    ADD_FEEBACK_ONE: 'ADD_FEEDBACK_ONE',
    ADD_FEEBACK_TWO: 'ADD_FEEDBACK_TWO',
    ADD_FEEBACK_THREE: 'ADD_FEEDBACK_THREE',
    ADD_FEEBACK_FOUR: 'ADD_FEEDBACK_FOUR',
    CLEAR_FEEDBACK_FORM: 'CLEAR_FEEDBACK_FORM',
}

export default FORM_ACTIONS;